[package]
name = "horsenuggets/luau-gl"
description = "A software graphics library for Luau."
version = "0.0.2"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/horsenuggets/luau-gl"
include = [
    "default.project.json",
    "init.luau",
    "LICENSE",
    "README.md",
    "Source",
    "Source/**",
    "wally.toml",
]
exclude = ["**"]

[dependencies]
PngLuau = "grilme99/png-luau@0.2.1"
t = "horsenuggets/t@3.1.1-horse.0.4"

[dev-dependencies]
Testable = "horsenuggets/testable@1.1.3"
